com.mehmetali.comic_manager.UserManager Class Reference
Public Member Functions
UserManager ()
String registerUser (User user)
boolean isUsernameAvailable (String username)
User login (String username, String password)
int creditbuyscore (String username, int credit)
int creditSellscore (String username, int credit)
int getUserWallet (String username)
Detailed Description
Manages user operations such as registration, login, and credit manipulation.
This class provides functionalities to manage users including registration, login, and manipulation of user credits.
Author
mehmetali
Version
1.0
Definition at line 20 of file UserManager.java.
Constructor & Destructor Documentation
UserManager()
com.mehmetali.comic_manager.UserManager.UserManager ()
Constructs a UserManager and reads users from the file.
Definition at line 29 of file UserManager.java.
                       {
    this.users = readUsersFromFile();
  }
Member Function Documentation
creditbuyscore()
int com.mehmetali.comic_manager.UserManager.creditbuyscore (String username, int credit)
Increases the wallet balance of a user.
Parameters
username the username of the user
credit the amount of credit to add to the wallet
Returns
the new wallet balance of the user, or -1 if the user is not found
Definition at line 138 of file UserManager.java.
                                                         {
    User foundUser = null;
    for (User user : users) {
      if (user.getUsername().equals(username)) {
        foundUser = user;
        break;
      }
    }
    if (foundUser == null) {
      System.out.println("User not found.");
      return -1;
    }
    int currentWallet = foundUser.getWallet();
    int newWallet = currentWallet + credit;
    foundUser.setWallet(newWallet);
    saveUsersToFile(users);
    return newWallet;
  }
References com.mehmetali.comic_manager.User< Comic >.getWallet(), and com.mehmetali.comic_manager.User< Comic >.setWallet().
Referenced by com.mehmetali.comic_manager.TradeManager.BuyTradeByID(), and com.mehmetali.comic_manager.Main.CreditBuyScoreMenu().
creditSellscore()
int com.mehmetali.comic_manager.UserManager.creditSellscore (String username, int credit)
Decreases the wallet balance of a user.
Parameters
username the username of the user
credit the amount of credit to deduct from the wallet
Returns
the new wallet balance of the user, or -1 if the user is not found
Definition at line 167 of file UserManager.java.
                                                          {
    User foundUser = null;
    for (User user : users) {
      if (user.getUsername().equals(username)) {
        foundUser = user;
        break;
      }
    }
    if (foundUser == null) {
      System.out.println("User not found.");
      return -1;
    }
    int currentWallet = foundUser.getWallet();
    int newWallet = currentWallet - credit;
    foundUser.setWallet(newWallet);
    saveUsersToFile(users);
    return newWallet;
  }
References com.mehmetali.comic_manager.User< Comic >.getWallet(), and com.mehmetali.comic_manager.User< Comic >.setWallet().
Referenced by com.mehmetali.comic_manager.TradeManager.BuyTradeByID().
getUserWallet()
int com.mehmetali.comic_manager.UserManager.getUserWallet (String username)
Gets the wallet balance of a user.
Parameters
username the username of the user
Returns
the wallet balance of the user, or -1 if the user is not found
Definition at line 194 of file UserManager.java.
                                            {
    for (User user : users) {
      if (user.getUsername().equals(username)) {
        return user.getWallet();
      }
    }
    return -1;
  }
isUsernameAvailable()
boolean com.mehmetali.comic_manager.UserManager.isUsernameAvailable (String username)
Checks if a username is available.
Parameters
username the username to check
Returns
true if the username is available, false otherwise
Definition at line 57 of file UserManager.java.
                                                      {
    for (User user : users) {
      if (user.getUsername().equals(username)) {
        return false;
      }
    }
    return true;
  }
Referenced by com.mehmetali.comic_manager.UserManager.registerUser().
login()
User com.mehmetali.comic_manager.UserManager.login (String username, String password)
Logs in a user with the given username and password.
Parameters
username the username of the user
password the password of the user
Returns
the user object if login is successful, null otherwise
Definition at line 121 of file UserManager.java.
                                                      {
    for (User user : users) {
      if (user.getUsername().equals(username) && user.getPassword().equals(password)) {
        return user;
      }
    }
    return null;
  }
Referenced by com.mehmetali.comic_manager.Main.loginMenu().
registerUser()
String com.mehmetali.comic_manager.UserManager.registerUser (User user)
Registers a new user.
Parameters
user the user to register
Returns
the username of the registered user, or null if registration fails
Definition at line 39 of file UserManager.java.
                                        {
    if (!isUsernameAvailable(user.getUsername())) {
      System.out.println("This username is already in use. Please choose a different username.");
      return null;
    }
    users.add(user);
    saveUsersToFile(users);
    System.out.println("User registered successfully.");
    return user.getUsername();
  }
References com.mehmetali.comic_manager.User< Comic >.getUsername(), and com.mehmetali.comic_manager.UserManager.isUsernameAvailable().
Referenced by com.mehmetali.comic_manager.Main.registerMenu().
The documentation for this class was generated from the following file:
comic_manager_app/src/main/java/com/mehmetali/comic_manager/UserManager.java