com.mehmetali.comic_manager.WishManager Class Reference
Classes
interface WishWriter
Public Member Functions
WishManager ()
int AddBook (Wish comic)
int listBooks ()
int listBooksByUser (String User)
int deleteBookByID (int bookID)
boolean isBookNameAvailable (String title)
Detailed Description
Manages the wish list of comics.
This class provides functionalities to manage the wish list of comics, including reading from and writing to a file, and interacting with the BookManager.
The class also includes an interface for writing wish data to a file.
Author
mehmetali
Version
1.0
Definition at line 24 of file WishManager.java.
Constructor & Destructor Documentation
WishManager()
com.mehmetali.comic_manager.WishManager.WishManager ()
Constructs a WishManager object and reads wish list from file.
Definition at line 50 of file WishManager.java.
                       {
    this.comics = readFromFile(WISH_FILE_PATH);
  }
Member Function Documentation
AddBook()
int com.mehmetali.comic_manager.WishManager.AddBook (Wish comic)
Adds a book wish to the wish list.
Parameters
comic the wish to add
Returns
the title of the added wish
Definition at line 61 of file WishManager.java.
                                 {
      
    if (!isBookNameAvailable(comic.getTitle())) {
      System.out.println("This Book name is already in use. Please choose a different book title.");
      return -1;
    }
    comicmanager.getBookTitleByID(comic.getComicID());
    //comic.setTitle(Name);
    comics.add(comic);
    writeToFile(comics, WISH_FILE_PATH);
    System.out.println("The book has been successfully added to the wish list.");
    return 0;
  }
References com.mehmetali.comic_manager.BookManager.getBookTitleByID(), com.mehmetali.comic_manager.Wish.getComicID(), com.mehmetali.comic_manager.Wish.getTitle(), and com.mehmetali.comic_manager.WishManager.isBookNameAvailable().
Referenced by com.mehmetali.comic_manager.Main.WishAddBookMenu().
deleteBookByID()
int com.mehmetali.comic_manager.WishManager.deleteBookByID (int bookID)
Deletes a book wish from the wish list by its ID.
Parameters
bookID the ID of the book to delete
Returns
0 if the book is deleted successfully, -1 otherwise
Definition at line 139 of file WishManager.java.
                                        {
    boolean found = false;
    for (Wish comic : comics) {
      if (comic.getComicID() == bookID) {
        comics.remove(comic);
        writeToFile(comics, WISH_FILE_PATH);
        System.out.println("Book deleted successfully.");
        found = true;
        return 0;
      }
    }
    if (!found) {
      System.out.println("No book matching book ID was found.");
      return -1;
    }
    return -1;
  }
Referenced by com.mehmetali.comic_manager.Main.WishdeleteBookMenu().
isBookNameAvailable()
boolean com.mehmetali.comic_manager.WishManager.isBookNameAvailable (String title)
Checks if a book name is available in the wish list.
Parameters
title the title to check
Returns
true if the title is available, false otherwise
Definition at line 172 of file WishManager.java.
                                                   {
    for (Wish comic : comics) {
      if (comic.getTitle().equals(title)) {
        return false;
      }
    }
    return true;
  }
Referenced by com.mehmetali.comic_manager.WishManager.AddBook().
listBooks()
int com.mehmetali.comic_manager.WishManager.listBooks ()
Lists all books in the wish list.
Returns
the number of books listed
Definition at line 81 of file WishManager.java.
                         {
    this.comics = readFromFile(WISH_FILE_PATH);
    if (comics.isEmpty()) {
      System.out.println("No books found to list.");
      return 0;
    }
    System.out.println("----- Book List -----");
    for (Wish comic : comics) {
      System.out.println("Book ID: " + comic.getComicID());
      System.out.println("Title: " + comic.getTitle());
      System.out.println("Page Number: " + comic.getpageNumber());
      System.out.println("Situation: " + comic.getuser());
      System.out.println("Value: " + comic.getValue());
      System.out.println("-------------------------");
    }
    return comics.size();
  }
listBooksByUser()
int com.mehmetali.comic_manager.WishManager.listBooksByUser (String User)
Lists books in the wish list owned by a specific user.
Parameters
user the username of the user
Returns
the number of books listed
Definition at line 109 of file WishManager.java.
                                          {
    this.comics = readFromFile(WISH_FILE_PATH);
    if (comics.isEmpty()) {
      System.out.println("No books found to list.");
      return 0;
    }
    System.out.println("----- " + User + " Books in Condition -----");
    for (Wish comic : comics) {
      if (comic.getuser().equalsIgnoreCase(User)) {
        System.out.println("Book ID: " + comic.getComicID());
        System.out.println("Title: " + comic.getTitle());
        System.out.println("Page Number: " + comic.getpageNumber());
        System.out.println("Situation: " + comic.getuser());
        System.out.println("Value: " + comic.getValue());
        System.out.println("-------------------------");
      }
    }
    return comics.size();
  }
Referenced by com.mehmetali.comic_manager.Main.WishlistBookMenu().
The documentation for this class was generated from the following file:
comic_manager_app/src/main/java/com/mehmetali/comic_manager/WishManager.java