com.mehmetali.comic_manager.Main Class Reference
Static Public Member Functions
static void clearConsole ()
static void main (String[] args) throws IOException
static int MainApp (Scanner scanner, PrintStream out) throws IOException
static int registerMenu (Scanner scanner, PrintStream out) throws IOException
static int AddBookMenu (Scanner scanner, PrintStream out) throws IOException
static int listBookMenu (Scanner scanner, PrintStream out) throws IOException
static int listAllBookMenu (Scanner scanner, PrintStream out) throws IOException
static int deleteBookMenu (Scanner scanner, PrintStream out) throws IOException
static int updateBookMenu (Scanner scanner, PrintStream out) throws IOException
static int WishAddBookMenu (Scanner scanner, PrintStream out) throws IOException
static int WishlistBookMenu (Scanner scanner, PrintStream out) throws IOException
static int WishdeleteBookMenu (Scanner scanner, PrintStream out) throws IOException
static int TradeAddBookMenu (Scanner scanner, PrintStream out) throws IOException
static int TradeMylistBookMenu (Scanner scanner, PrintStream out) throws IOException
static int TradedeleteBookMenu (Scanner scanner, PrintStream out) throws IOException
static int TradeAllListBookMenu (Scanner scanner, PrintStream out) throws IOException
static int TradeBuyBookMenu (Scanner scanner, PrintStream out) throws IOException
static int CreditBuyScoreMenu (Scanner scanner, PrintStream out) throws IOException
static int EventAddBookMenu (Scanner scanner, PrintStream out) throws IOException
static int EventlistBookMenu (Scanner scanner, PrintStream out) throws IOException
static int EventlistAllBookMenu (Scanner scanner, PrintStream out) throws IOException
static int EventdeleteBookMenu (Scanner scanner, PrintStream out) throws IOException
static int EventupdateBookMenu (Scanner scanner, PrintStream out) throws IOException
static User loginMenu (Scanner scanner, PrintStream out) throws IOException
static int userMenu (User user, Scanner scanner, PrintStream out) throws IOException
static String getLoginName ()
static void setLoginName (String loginName)
static int getWallet ()
static void setWallet (int loginWallet)
Static Public Attributes
static String LoginName
static int LoginWallet
static boolean control = false
Detailed Description
Main class for managing the comic manager application. This class provides methods for user interaction and menu navigation.
The Main class serves as the entry point for the application and orchestrates user interaction.
Author
mehmetali
Version
1.0
Definition at line 22 of file Main.java.
Member Function Documentation
AddBookMenu()
static int com.mehmetali.comic_manager.Main.AddBookMenu (Scanner scanner, PrintStream out) throws IOException [static]
Adds a new book to the book management system.
Parameters
scanner A Scanner object for user input.
out A PrintStream object for output.
Returns
Returns 0 upon successful addition of the book.
Exceptions
IOException Signals that an I/O exception has occurred.
Definition at line 229 of file Main.java.
                                                                                     {
    System.out.print("Book ID: ");
    int bookId = scanner.nextInt();
    scanner.nextLine();
    System.out.print("Book Name: ");
    String bookName = scanner.nextLine();
    System.out.print("Book Page Number: ");
    int bookpage = scanner.nextInt();
    System.out.print("Book Value: ");
    int bookvalue = scanner.nextInt();
    Book newUser = new Book(bookId, bookName,bookpage,LoginName,bookvalue);
    comicmanager.AddBook(newUser);
    return 0;
  }
References com.mehmetali.comic_manager.BookManager.AddBook(), and com.mehmetali.comic_manager.Main.LoginName.
Referenced by com.mehmetali.comic_manager.Main.userMenu().
clearConsole()
static void com.mehmetali.comic_manager.Main.clearConsole () [static]
Clears the console screen.
On Windows, it uses the `cls` command through the command prompt. On Unix/Linux/Mac systems, it clears the console screen by printing specific escape characters.
Definition at line 120 of file Main.java.
                                    {
    try {
      // Windows
      if (System.getProperty("os.name").contains("Windows")) {
        new ProcessBuilder("cmd", "/c", "cls").inheritIO().start().waitFor();
      }
      // Unix/Linux/Mac
      else {
        System.out.print("\033[H\033[2J");
        System.out.flush();
      }
    } catch (IOException | InterruptedException ex) {
      // Handle exception
      ex.printStackTrace();
    }
  }
Referenced by com.mehmetali.comic_manager.Main.loginMenu(), and com.mehmetali.comic_manager.Main.userMenu().
CreditBuyScoreMenu()
static int com.mehmetali.comic_manager.Main.CreditBuyScoreMenu (Scanner scanner, PrintStream out) throws IOException [static]
Increases the user's credit score by the specified amount.
Parameters
scanner A Scanner object for user input.
out A PrintStream object for output.
Returns
Returns 0 upon successful update of the user's credit score.
Exceptions
IOException Signals that an I/O exception has occurred.
Definition at line 481 of file Main.java.
                                                                                            {
    out.println("Credit Score:");
    int score = scanner.nextInt();
    userManager.creditbuyscore(LoginName, score);
    return 0;
  }
References com.mehmetali.comic_manager.UserManager.creditbuyscore(), and com.mehmetali.comic_manager.Main.LoginName.
Referenced by com.mehmetali.comic_manager.Main.userMenu().
deleteBookMenu()
static int com.mehmetali.comic_manager.Main.deleteBookMenu (Scanner scanner, PrintStream out) throws IOException [static]
Deletes a book from the system by its ID.
Parameters
scanner A Scanner object for user input.
out A PrintStream object for output.
Returns
Returns 0 upon successful deletion of the book.
Exceptions
IOException Signals that an I/O exception has occurred.
Definition at line 280 of file Main.java.
                                                                                        {
    out.print("Book ID: ");
    int bookId = scanner.nextInt();
    comicmanager.deleteBookByID(bookId);
    return 0;
  }
References com.mehmetali.comic_manager.BookManager.deleteBookByID().
Referenced by com.mehmetali.comic_manager.Main.userMenu().
EventAddBookMenu()
static int com.mehmetali.comic_manager.Main.EventAddBookMenu (Scanner scanner, PrintStream out) throws IOException [static]
Adds a new event to the event management system.
Parameters
scanner A Scanner object for user input.
out A PrintStream object for output.
Returns
Returns 0 upon successful addition of the event.
Exceptions
IOException Signals that an I/O exception has occurred.
Definition at line 498 of file Main.java.
                                                                                          {
    // Prompting user for event details
    out.print("Event ID: ");
    int eventId = scanner.nextInt();
    scanner.nextLine(); // Consume newline character
    out.print("Event Name: ");
    String eventName = scanner.nextLine();
    out.print("Event Content: ");
    String eventContent = scanner.nextLine();
    // Creating a new Event object with the provided details
    Event newEvent = new Event(eventId, eventName, eventContent, LoginName);
    // Adding the new event to the event management system
    eventmanager.AddEvent(newEvent);
    return 0; // Returning 0 to indicate successful addition
  }
References com.mehmetali.comic_manager.EventManager.AddEvent(), and com.mehmetali.comic_manager.Main.LoginName.
Referenced by com.mehmetali.comic_manager.Main.userMenu().
EventdeleteBookMenu()
static int com.mehmetali.comic_manager.Main.EventdeleteBookMenu (Scanner scanner, PrintStream out) throws IOException [static]
Deletes an event from the event management system by its ID.
Parameters
scanner A Scanner object for user input.
out A PrintStream object for output.
Returns
Returns 0 upon successful deletion of the event.
Exceptions
IOException Signals that an I/O exception has occurred.
Definition at line 551 of file Main.java.
                                                                                             {
    out.print("Event ID: ");
    int eventId = scanner.nextInt();
    // Deleting the event from the event management system
    eventmanager.deleteEventByID(eventId);
    return 0;
  }
References com.mehmetali.comic_manager.EventManager.deleteEventByID().
Referenced by com.mehmetali.comic_manager.Main.userMenu().
EventlistAllBookMenu()
static int com.mehmetali.comic_manager.Main.EventlistAllBookMenu (Scanner scanner, PrintStream out) throws IOException [static]
Displays the list of all events in the system.
Parameters
scanner A Scanner object for user input.
out A PrintStream object for output.
Returns
Returns 0 upon successful display of all events.
Exceptions
IOException Signals that an I/O exception has occurred.
Definition at line 536 of file Main.java.
                                                                                              {
    out.println("Event All List");
    eventmanager.listEvents();
    return 0;
  }
References com.mehmetali.comic_manager.EventManager.listEvents().
Referenced by com.mehmetali.comic_manager.Main.userMenu().
EventlistBookMenu()
static int com.mehmetali.comic_manager.Main.EventlistBookMenu (Scanner scanner, PrintStream out) throws IOException [static]
Displays the list of events related to the current user.
Parameters
scanner A Scanner object for user input.
out A PrintStream object for output.
Returns
Returns 0 upon successful display of the event list.
Exceptions
IOException Signals that an I/O exception has occurred.
Definition at line 522 of file Main.java.
                                                                                           {
    out.println("Event List");
    eventmanager.listEventsByCondition(LoginName);
    return 0;
  }
References com.mehmetali.comic_manager.EventManager.listEventsByCondition(), and com.mehmetali.comic_manager.Main.LoginName.
Referenced by com.mehmetali.comic_manager.Main.userMenu().
EventupdateBookMenu()
static int com.mehmetali.comic_manager.Main.EventupdateBookMenu (Scanner scanner, PrintStream out) throws IOException [static]
Updates the details of an event in the event management system by its ID.
Parameters
scanner A Scanner object for user input.
out A PrintStream object for output.
Returns
Returns 0 upon successful update of the event details.
Exceptions
IOException Signals that an I/O exception has occurred.
Definition at line 567 of file Main.java.
                                                                                             {
    // Prompting user for the ID of the event to be updated
    out.print("Event ID: ");
    int eventId = scanner.nextInt();
    scanner.nextLine(); // Consume newline character
    // Prompting user for the new details of the event
    out.print("New Event Name: ");
    String eventName = scanner.nextLine();
    out.print("New Event Content: ");
    String eventContent = scanner.nextLine();
    // Updating the details of the event in the event management system
    eventmanager.updateEventTitleByID(eventId, eventName, eventContent);
    return 0; // Returning 0 to indicate successful update
  }
References com.mehmetali.comic_manager.EventManager.updateEventTitleByID().
Referenced by com.mehmetali.comic_manager.Main.userMenu().
getLoginName()
static String com.mehmetali.comic_manager.Main.getLoginName () [static]
Returns the login name of the current user.
Returns
The login name of the current user.
Definition at line 991 of file Main.java.
                                      {
    return LoginName;
  }
References com.mehmetali.comic_manager.Main.LoginName.
getWallet()
static int com.mehmetali.comic_manager.Main.getWallet () [static]
Returns the wallet balance of the current user.
Returns
The wallet balance of the current user.
Definition at line 1009 of file Main.java.
                                {
    return LoginWallet;
  }
References com.mehmetali.comic_manager.Main.LoginWallet.
listAllBookMenu()
static int com.mehmetali.comic_manager.Main.listAllBookMenu (Scanner scanner, PrintStream out) throws IOException [static]
Displays the list of all books in the system.
Parameters
scanner A Scanner object for user input.
out A PrintStream object for output.
Returns
Returns 0 upon successful display of the book list.
Exceptions
IOException Signals that an I/O exception has occurred.
Definition at line 266 of file Main.java.
                                                                                         {
    out.println("Book All List");
    comicmanager.listBooks();
    return 0;
  }
References com.mehmetali.comic_manager.BookManager.listBooks().
Referenced by com.mehmetali.comic_manager.Main.userMenu().
listBookMenu()
static int com.mehmetali.comic_manager.Main.listBookMenu (Scanner scanner, PrintStream out) throws IOException [static]
Displays the list of books owned by the current user.
Parameters
scanner A Scanner object for user input.
out A PrintStream object for output.
Returns
Returns 0 upon successful display of the book list.
Exceptions
IOException Signals that an I/O exception has occurred.
Definition at line 252 of file Main.java.
                                                                                      {
    out.println("Book List");
    comicmanager.listBooksByCondition(LoginName);
    return 0;
  }
References com.mehmetali.comic_manager.BookManager.listBooksByCondition(), and com.mehmetali.comic_manager.Main.LoginName.
Referenced by com.mehmetali.comic_manager.Main.userMenu().
loginMenu()
static User com.mehmetali.comic_manager.Main.loginMenu (Scanner scanner, PrintStream out) throws IOException [static]
Handles the login process for the user.
Parameters
scanner Scanner object to read user input.
out PrintStream object to display output to the user.
Returns
User object representing the logged-in user, or null if login fails.
Exceptions
IOException if an I/O error occurs. Allows a user to log in to the system using their username and password.
Parameters
scanner A Scanner object for user input.
out A PrintStream object for output.
Returns
Returns the User object corresponding to the logged-in user if successful, or null if the login attempt fails.
Exceptions
IOException Signals that an I/O exception has occurred.
Definition at line 631 of file Main.java.
                                                                                    {
    // Prompting user for username and password
    out.print("UserName: ");
    String username = scanner.nextLine();
    out.print("Password: ");
    String password = scanner.nextLine();
    // Attempting to log in the user
    User user = userManager.login(username, password);
    // Displaying login result
    if (user != null) {
      clearConsole();
      out.println("Hello, " + user.getUsername() + "!");
    } else {
      clearConsole();
      out.println("Username or password is wrong!");
    }
    return user; // Returning the logged-in user object or null if login fails
  }
References com.mehmetali.comic_manager.Main.clearConsole(), com.mehmetali.comic_manager.User< Comic >.getUsername(), and com.mehmetali.comic_manager.UserManager.login().
Referenced by com.mehmetali.comic_manager.Main.MainApp().
main()
static void com.mehmetali.comic_manager.Main.main (String[] args) throws IOException [static]
The entry point of the application.
Parameters
args The command line arguments.
Exceptions
IOException If an I/O error occurs.
Definition at line 143 of file Main.java.
                                                            {
    Scanner scanner = new Scanner(System.in);
    MainApp(scanner, System.out);
  }
References com.mehmetali.comic_manager.Main.MainApp().
MainApp()
static int com.mehmetali.comic_manager.Main.MainApp (Scanner scanner, PrintStream out) throws IOException [static]
Runs the main application loop.
Parameters
scanner The scanner object for input.
out The output stream for printing.
Returns
An integer indicating the success status of the application.
Exceptions
IOException If an I/O error occurs.
Definition at line 157 of file Main.java.
                                                                                 {
    boolean exit = false;
    while (!exit) {
      control = true;
      String title = "MAIN MENU";
      String[] options = {
        "1. Register",
        "2. Login",
        "3. Exit"
      };
      printMenu(title, options);
      int choice = scanner.nextInt();
      scanner.nextLine();
      control = false;
      switch (choice) {
        case 1:
          registerMenu(scanner, System.out);
          break;
        case 2:
          User loggedInUser = loginMenu(scanner, System.out);
          setLoginName(loggedInUser.getUsername());
          setWallet(loggedInUser.getWallet());
          if (loggedInUser != null) {
            //clearConsole();
            userMenu(loggedInUser,scanner, System.out);
          }
          break;
        case 3:
          exit = true;
          break;
      }
    }
    scanner.close();
    return 0;
  }
References com.mehmetali.comic_manager.Main.control, com.mehmetali.comic_manager.User< Comic >.getUsername(), com.mehmetali.comic_manager.User< Comic >.getWallet(), com.mehmetali.comic_manager.Main.loginMenu(), com.mehmetali.comic_manager.Main.registerMenu(), com.mehmetali.comic_manager.Main.setLoginName(), com.mehmetali.comic_manager.Main.setWallet(), and com.mehmetali.comic_manager.Main.userMenu().
Referenced by com.mehmetali.comic_manager.Main.main().
registerMenu()
static int com.mehmetali.comic_manager.Main.registerMenu (Scanner scanner, PrintStream out) throws IOException [static]
Registers a new user.
Parameters
scanner The scanner object for input.
out The output stream for printing.
Returns
An integer indicating the success status of the registration process.
Exceptions
IOException If an I/O error occurs.
Definition at line 210 of file Main.java.
                                                                                      {
    System.out.print("UserName: ");
    String username = scanner.nextLine();
    System.out.print("Password: ");
    String password = scanner.nextLine();
    User newUser = new User(username, password, 0);
    userManager.registerUser(newUser);
    return 0;
  }
References com.mehmetali.comic_manager.UserManager.registerUser().
Referenced by com.mehmetali.comic_manager.Main.MainApp().
setLoginName()
static void com.mehmetali.comic_manager.Main.setLoginName (String loginName) [static]
Sets the login name of the current user.
Parameters
loginName The login name to be set.
Definition at line 1000 of file Main.java.
                                                    {
    LoginName = loginName;
  }
References com.mehmetali.comic_manager.Main.LoginName.
Referenced by com.mehmetali.comic_manager.Main.MainApp().
setWallet()
static void com.mehmetali.comic_manager.Main.setWallet (int loginWallet) [static]
Sets the wallet balance of the current user.
Parameters
loginWallet The wallet balance to be set.
Definition at line 1018 of file Main.java.
                                                {
    LoginWallet = loginWallet;
  }
References com.mehmetali.comic_manager.Main.LoginWallet.
Referenced by com.mehmetali.comic_manager.Main.MainApp().
TradeAddBookMenu()
static int com.mehmetali.comic_manager.Main.TradeAddBookMenu (Scanner scanner, PrintStream out) throws IOException [static]
Adds a book to the trade list of the current user and removes it from their collection.
Parameters
scanner A Scanner object for user input.
out A PrintStream object for output.
Returns
Returns 0 upon successful addition of the book to the trade list.
Exceptions
IOException Signals that an I/O exception has occurred.
Definition at line 391 of file Main.java.
                                                                                          {
    out.print("Book ID: ");
    int bookId = scanner.nextInt();
    // Retrieving book details for trade list entry
    int pageNumber = comicmanager.getBookPageNumberByID(bookId);
    String title = comicmanager.getBookTitleByID(bookId);
    int value = comicmanager.getBookValueByID(bookId);
    // Creating a new Trade object and adding it to the trade list
    Trade newUser = new Trade(bookId, title, pageNumber, LoginName, value);
    trademanager.AddTrade(newUser);
    // Deleting the book from the collection
    comicmanager.deleteBookByID(bookId);
    return 0; // Returning 0 to indicate successful addition to the trade list
  }
References com.mehmetali.comic_manager.TradeManager.AddTrade(), com.mehmetali.comic_manager.BookManager.deleteBookByID(), com.mehmetali.comic_manager.BookManager.getBookPageNumberByID(), com.mehmetali.comic_manager.BookManager.getBookTitleByID(), com.mehmetali.comic_manager.BookManager.getBookValueByID(), and com.mehmetali.comic_manager.Main.LoginName.
Referenced by com.mehmetali.comic_manager.Main.userMenu().
TradeAllListBookMenu()
static int com.mehmetali.comic_manager.Main.TradeAllListBookMenu (Scanner scanner, PrintStream out) throws IOException [static]
Displays the list of all books available for trade.
Parameters
scanner A Scanner object for user input.
out A PrintStream object for output.
Returns
Returns 0 upon successful display of the trade list.
Exceptions
IOException Signals that an I/O exception has occurred.
Definition at line 444 of file Main.java.
                                                                                              {
    out.println("Book List");
    trademanager.listAllTradeList();
    return 0;
  }
References com.mehmetali.comic_manager.TradeManager.listAllTradeList().
Referenced by com.mehmetali.comic_manager.Main.userMenu().
TradeBuyBookMenu()
static int com.mehmetali.comic_manager.Main.TradeBuyBookMenu (Scanner scanner, PrintStream out) throws IOException [static]
Buys a book from the trade list by its ID if the user's credit score is sufficient.
Parameters
scanner A Scanner object for user input.
out A PrintStream object for output.
Returns
Returns 0 upon successful purchase of the book, or -1 if the user's credit score is insufficient.
Exceptions
IOException Signals that an I/O exception has occurred.
Definition at line 458 of file Main.java.
                                                                                          {
    out.print("Book ID: ");
    int bookId = scanner.nextInt();
    // Checking if the user's credit score is sufficient to buy the book
    if (LoginWallet >= trademanager.getBookValueByID(bookId)) {
      trademanager.BuyTradeByID(bookId);
    } else {
      out.println("Credit Score Insufficient! Could not purchase.");
      return -1;
    }
    return 0;
  }
References com.mehmetali.comic_manager.TradeManager.BuyTradeByID(), com.mehmetali.comic_manager.TradeManager.getBookValueByID(), and com.mehmetali.comic_manager.Main.LoginWallet.
Referenced by com.mehmetali.comic_manager.Main.userMenu().
TradedeleteBookMenu()
static int com.mehmetali.comic_manager.Main.TradedeleteBookMenu (Scanner scanner, PrintStream out) throws IOException [static]
Deletes a book from the trade list by its ID.
Parameters
scanner A Scanner object for user input.
out A PrintStream object for output.
Returns
Returns 0 upon successful deletion of the book from the trade list.
Exceptions
IOException Signals that an I/O exception has occurred.
Definition at line 428 of file Main.java.
                                                                                             {
    out.print("Book ID: ");
    int bookId = scanner.nextInt();
    trademanager.deleteTradeByID(bookId);
    return 0;
  }
References com.mehmetali.comic_manager.TradeManager.deleteTradeByID().
Referenced by com.mehmetali.comic_manager.Main.userMenu().
TradeMylistBookMenu()
static int com.mehmetali.comic_manager.Main.TradeMylistBookMenu (Scanner scanner, PrintStream out) throws IOException [static]
Displays the trade list of books owned by the current user.
Parameters
scanner A Scanner object for user input.
out A PrintStream object for output.
Returns
Returns 0 upon successful display of the trade list.
Exceptions
IOException Signals that an I/O exception has occurred.
Definition at line 414 of file Main.java.
                                                                                             {
    // Displaying the trade list of the current user
    trademanager.listMyTradeList(LoginName);
    return 0;
  }
References com.mehmetali.comic_manager.TradeManager.listMyTradeList(), and com.mehmetali.comic_manager.Main.LoginName.
Referenced by com.mehmetali.comic_manager.Main.userMenu().
updateBookMenu()
static int com.mehmetali.comic_manager.Main.updateBookMenu (Scanner scanner, PrintStream out) throws IOException [static]
Updates the details of a book in the system by its ID.
Parameters
scanner A Scanner object for user input.
out A PrintStream object for output.
Returns
Returns 0 upon successful update of the book details.
Exceptions
IOException Signals that an I/O exception has occurred.
Definition at line 296 of file Main.java.
                                                                                        {
    // Prompting user for the ID of the book to be updated
    out.print("Book ID: ");
    int bookId = scanner.nextInt();
    scanner.nextLine(); // Consume newline character
    // Prompting user for the new details of the book
    out.print("New Book Name: ");
    String bookName = scanner.nextLine();
    out.print("New Book Page Number: ");
    int bookpage = scanner.nextInt();
    scanner.nextLine(); // Consume newline character
    out.print("New Book Value: ");
    int bookvalue = scanner.nextInt();
    scanner.nextLine(); // Consume newline character
    // Updating the details of the book in the system
    comicmanager.updateBookTitleByID(bookId, bookName, bookpage, bookvalue);
    return 0; // Returning 0 to indicate successful update
  }
References com.mehmetali.comic_manager.BookManager.updateBookTitleByID().
Referenced by com.mehmetali.comic_manager.Main.userMenu().
userMenu()
static int com.mehmetali.comic_manager.Main.userMenu (User user, Scanner scanner, PrintStream out) throws IOException [static]
Displays the user menu and allows the user to interact with the system based on their role.
Parameters
user The User object representing the currently logged-in user.
scanner A Scanner object for user input.
out A PrintStream object for output.
Returns
Returns 0 upon successful completion of user interaction.
Exceptions
IOException Signals that an I/O exception has occurred.
Definition at line 662 of file Main.java.
                                                                                            {
    boolean exit = false;
    while (!exit) {
      String title = "USER MENU";
      String[] options = {
        "1. Cataloging Comic Book Collection",
        "2. Wishlist and Trade List Management",
        "3. Comic Book Events and Conventions",
        "4. Buy Credit Score",
        "5. Exit"
      };
      printMenu(title, options);
      int choice = scanner.nextInt();
      scanner.nextLine();
      while (choice != 6) {
        switch (choice) {
          case 1:
            clearConsole();
            System.out.println("Cataloging Comic Book Collection");
            String title2 = "MY BOOK MENU";
            String[] options2 = {
              "1. My Book Add",
              "2. My Book Delete",
              "3. My Book Update",
              "4. My Book List",
              "5. All Book List",
              "6. Exit"
            };
            printMenu(title2, options2);
            int choice2 = scanner.nextInt();
            scanner.nextLine();
            switch (choice2) {
              case 1:
                //clearConsole();
                AddBookMenu(scanner, System.out);
                break;
              case 2:
                //clearConsole();
                deleteBookMenu(scanner, System.out);
                break;
              case 3:
                //clearConsole();
                updateBookMenu(scanner, System.out);
                break;
              case 4:
                clearConsole();
                listBookMenu(scanner, System.out);
                break;
              case 5:
                clearConsole();
                listAllBookMenu(scanner, System.out);
                break;
              case 6:
                choice = 5;
                break;
            }
            break;
          case 2:
            clearConsole();
            System.out.println("Wishlist and Trade List Management");
            String title3 = "WISHLIST OR TRADE MENU";
            String[] options3 = {
              "1. My Wish List",
              "2. My Trade List",
              "3. Exit"
            };
            printMenu(title3, options3);
            int choice3 = scanner.nextInt();
            scanner.nextLine();
            switch (choice3) {
              case 1:
                clearConsole();
                String title4 = "MY WISHLIST MENU";
                String[] options4 = {
                  "1. My Wish Book Add",
                  "2. My Wish Book Delete",
                  "3. My Wish Book List",
                  "4. My Book List",
                  "5. Return",
                  "5. Exit"
                };
                printMenu(title4, options4);
                int choice4 = scanner.nextInt();
                scanner.nextLine();
                switch (choice4) {
                  case 1:
                    clearConsole();
                    WishAddBookMenu(scanner, System.out);
                    break;
                  case 2:
                    clearConsole();
                    WishdeleteBookMenu(scanner, System.out);
                    break;
                  case 3:
                    clearConsole();
                    WishlistBookMenu(scanner, System.out);
                    break;
                  case 4:
                    clearConsole();
                    listBookMenu(scanner, System.out);
                    break;
                  case 5:
                    choice = 5;
                    break;
                  case 6:
                    break;
                }
                break;
              case 2:
                clearConsole();
                String title5 = "MY TRADE MENU";
                String[] options5 = {
                  "1. Buy Book",
                  "2. Sell Book",
                  "3. Return",
                  "4. Exit"
                };
                printMenu(title5, options5);
                int choice5 = scanner.nextInt();
                scanner.nextLine();
                switch(choice5) {
                  case 1:
                    clearConsole();
                    String title6 = "MY BUY MENU";
                    String[] options6 = {
                      "1. Buy New Book",
                      "2. Trade Book List",
                      "3. Return",
                      "4. Exit"
                    };
                    printMenu(title6, options6);
                    int choice6 = scanner.nextInt();
                    scanner.nextLine();
                    switch(choice6) {
                      case 1:
                        clearConsole();
                        TradeBuyBookMenu(scanner, System.out);
                        break;
                      case 2:
                        clearConsole();
                        TradeAllListBookMenu(scanner, System.out);
                        break;
                      case 3:
                        choice = 5;
                        break;
                      case 4:
                        break;
                    }
                    break;
                  case 2:
                    String title7 = "MY SELL MENU";
                    String[] options7 = {
                      "1. Add Sell New Book",
                      "2. Delete Sell Book",
                      "3. Trade Book List",
                      "4. My Trade Book List",
                      "5. Return",
                      "6. Exit"
                    };
                    printMenu(title7, options7);
                    int choice7 = scanner.nextInt();
                    scanner.nextLine();
                    switch(choice7) {
                      case 1:
                        clearConsole();
                        TradeAddBookMenu(scanner, System.out);
                        break;
                      case 2:
                        clearConsole();
                        TradedeleteBookMenu(scanner, System.out);
                        break;
                      case 3:
                        clearConsole();
                        TradeAllListBookMenu(scanner, System.out);
                        break;
                      case 4:
                        clearConsole();
                        TradeMylistBookMenu(scanner, System.out);
                        break;
                      case 5:
                        choice = 5;
                        break;
                      case 6:
                        exit = true;
                        break;
                    }
                    break;
                  case 3:
                    choice = 5;
                    break;
                }
                break;
              case 3:
                choice = 5;
                break;
            }
            break;
          case 3:
            clearConsole();
            System.out.println("Comic Book Events and Conventions");
            String title8 = "MY EVENT MENU";
            String[] options8 = {
              "1. Add My Event",
              "2. Sell My Event",
              "3. Update My Event",
              "4. My Event List",
              "5. All Event List",
              "6. Return",
              "7. Exit"
            };
            printMenu(title8, options8);
            int choice8 = scanner.nextInt();
            scanner.nextLine();
            switch(choice8) {
              case 1:
                clearConsole();
                EventAddBookMenu(scanner, System.out);
                break;
              case 2:
                clearConsole();
                EventdeleteBookMenu(scanner, System.out);
                break;
              case 3:
                clearConsole();
                EventupdateBookMenu(scanner, System.out);
                break;
              case 4:
                clearConsole();
                EventlistBookMenu(scanner, System.out);
                break;
              case 5:
                clearConsole();
                EventlistAllBookMenu(scanner, System.out);
                break;
              case 6:
                choice = 5;
                break;
              case 7:
                break;
            }
            break;
          case 4:
            clearConsole();
            String title9 = "MY CREDIT SCORE MENU";
            String[] options9 = {
              "1. Buy Credit Score",
              "2. Exit"
            };
            printMenu(title9, options9);
            int choice9 = scanner.nextInt();
            scanner.nextLine();
            switch(choice9) {
              case 1:
                clearConsole();
                CreditBuyScoreMenu(scanner, System.out);
                break;
              case 2:
                choice = 5;
                break;
            }
            break;
          case 5:
            //System.exit(0);
            //return 0;
            return 0;
        }
      }
    }
    scanner.close();
    return 0;
  }
References com.mehmetali.comic_manager.Main.AddBookMenu(), com.mehmetali.comic_manager.Main.clearConsole(), com.mehmetali.comic_manager.Main.CreditBuyScoreMenu(), com.mehmetali.comic_manager.Main.deleteBookMenu(), com.mehmetali.comic_manager.Main.EventAddBookMenu(), com.mehmetali.comic_manager.Main.EventdeleteBookMenu(), com.mehmetali.comic_manager.Main.EventlistAllBookMenu(), com.mehmetali.comic_manager.Main.EventlistBookMenu(), com.mehmetali.comic_manager.Main.EventupdateBookMenu(), com.mehmetali.comic_manager.Main.listAllBookMenu(), com.mehmetali.comic_manager.Main.listBookMenu(), com.mehmetali.comic_manager.Main.TradeAddBookMenu(), com.mehmetali.comic_manager.Main.TradeAllListBookMenu(), com.mehmetali.comic_manager.Main.TradeBuyBookMenu(), com.mehmetali.comic_manager.Main.TradedeleteBookMenu(), com.mehmetali.comic_manager.Main.TradeMylistBookMenu(), com.mehmetali.comic_manager.Main.updateBookMenu(), com.mehmetali.comic_manager.Main.WishAddBookMenu(), com.mehmetali.comic_manager.Main.WishdeleteBookMenu(), and com.mehmetali.comic_manager.Main.WishlistBookMenu().
Referenced by com.mehmetali.comic_manager.Main.MainApp().
WishAddBookMenu()
static int com.mehmetali.comic_manager.Main.WishAddBookMenu (Scanner scanner, PrintStream out) throws IOException [static]
Adds a book to the wish list of the current user.
Parameters
scanner A Scanner object for user input.
out A PrintStream object for output.
Returns
Returns 0 upon successful addition of the book to the wish list, or -1 if the book ID is not available in the system.
Exceptions
IOException Signals that an I/O exception has occurred.
Definition at line 327 of file Main.java.
                                                                                         {
    // Prompting user for the ID of the book to be added to the wish list
    out.print("Book ID: ");
    int bookId = scanner.nextInt();
    scanner.nextLine(); // Consume newline character
    // Checking if the book ID is available in the system
    if (comicmanager.isBookIDAvailable(bookId)) {
      out.println("No such book found.");
      return -1; // Returning -1 if the book ID is not available
    }
    // Retrieving book details for wish list entry
    int pageNumber = comicmanager.getBookPageNumberByID(bookId);
    String title = comicmanager.getBookTitleByID(bookId);
    int value = comicmanager.getBookPageNumberByID(bookId);
    // Creating a new Wish object and adding it to the wish list
    Wish newUser = new Wish(bookId, title, pageNumber, LoginName, value);
    wishmanager.AddBook(newUser);
    return 0; // Returning 0 to indicate successful addition to the wish list
  }
References com.mehmetali.comic_manager.WishManager.AddBook(), com.mehmetali.comic_manager.BookManager.getBookPageNumberByID(), com.mehmetali.comic_manager.BookManager.getBookTitleByID(), com.mehmetali.comic_manager.BookManager.isBookIDAvailable(), and com.mehmetali.comic_manager.Main.LoginName.
Referenced by com.mehmetali.comic_manager.Main.userMenu().
WishdeleteBookMenu()
static int com.mehmetali.comic_manager.Main.WishdeleteBookMenu (Scanner scanner, PrintStream out) throws IOException [static]
Deletes a book from the wish list by its ID.
Parameters
scanner A Scanner object for user input.
out A PrintStream object for output.
Returns
Returns 0 upon successful deletion of the book from the wish list.
Exceptions
IOException Signals that an I/O exception has occurred.
Definition at line 372 of file Main.java.
                                                                                            {
    out.print("Book ID: ");
    int bookId = scanner.nextInt();
    wishmanager.deleteBookByID(bookId);
    return 0;
  }
References com.mehmetali.comic_manager.WishManager.deleteBookByID().
Referenced by com.mehmetali.comic_manager.Main.userMenu().
WishlistBookMenu()
static int com.mehmetali.comic_manager.Main.WishlistBookMenu (Scanner scanner, PrintStream out) throws IOException [static]
Displays the wish list of books owned by the current user.
Parameters
scanner A Scanner object for user input.
out A PrintStream object for output.
Returns
Returns 0 upon successful display of the wish list.
Exceptions
IOException Signals that an I/O exception has occurred.
Definition at line 358 of file Main.java.
                                                                                          {
    out.println("Wish Book List");
    wishmanager.listBooksByUser(LoginName);
    return 0;
  }
References com.mehmetali.comic_manager.WishManager.listBooksByUser(), and com.mehmetali.comic_manager.Main.LoginName.
Referenced by com.mehmetali.comic_manager.Main.userMenu().
Member Data Documentation
control
boolean com.mehmetali.comic_manager.Main.control = false [static]
Boolean variable indicating control status.
Definition at line 53 of file Main.java.
Referenced by com.mehmetali.comic_manager.Main.MainApp().
LoginName
String com.mehmetali.comic_manager.Main.LoginName [static]
The username of the logged-in user.
Definition at line 27 of file Main.java.
Referenced by com.mehmetali.comic_manager.Main.AddBookMenu(), com.mehmetali.comic_manager.TradeManager.BuyTradeByID(), com.mehmetali.comic_manager.Main.CreditBuyScoreMenu(), com.mehmetali.comic_manager.Main.EventAddBookMenu(), com.mehmetali.comic_manager.Main.EventlistBookMenu(), com.mehmetali.comic_manager.Main.getLoginName(), com.mehmetali.comic_manager.Main.listBookMenu(), com.mehmetali.comic_manager.Main.setLoginName(), com.mehmetali.comic_manager.Main.TradeAddBookMenu(), com.mehmetali.comic_manager.Main.TradeMylistBookMenu(), com.mehmetali.comic_manager.Main.WishAddBookMenu(), and com.mehmetali.comic_manager.Main.WishlistBookMenu().
LoginWallet
int com.mehmetali.comic_manager.Main.LoginWallet [static]
The wallet balance of the logged-in user.
Definition at line 32 of file Main.java.
Referenced by com.mehmetali.comic_manager.Main.getWallet(), com.mehmetali.comic_manager.Main.setWallet(), and com.mehmetali.comic_manager.Main.TradeBuyBookMenu().
The documentation for this class was generated from the following file:
comic_manager_app/src/main/java/com/mehmetali/comic_manager/Main.java