com.mehmetali.comic_manager.User< Comic > Class Template Reference
Public Member Functions
User (String username, String password, int wallet)
int getWallet ()
void setWallet (int wallet)
String getUsername ()
void setUsername (String username)
String getPassword ()
void setPassword (String password)
List< Comic > getCollection ()
void setCollection (List< Comic > collection)
List< Comic > getWishlist ()
void setWishlist (List< Comic > wishlist)
List< Comic > getTradeList ()
void setTradeList (List< Comic > tradeList)
void addToCollection (Comic comic)
void removeFromCollection (Comic comic)
void addToWishlist (Comic comic)
void removeFromWishlist (Comic comic)
void addToTradeList (Comic comic)
void removeFromTradeList (Comic comic)
String toString ()
Detailed Description
Represents a user in the comic management system.
This class represents a user in the comic management system. It contains information such as username, password, wallet balance, collection of comics, wishlist, and trade list.
The class implements the Serializable interface to support object serialization.
Author
mehmetali
Version
1.0
Parameters
<Comic> the type of comic in the user's collection, wishlist, and trade list
Definition at line 23 of file User.java.
Constructor & Destructor Documentation
User()
com.mehmetali.comic_manager.User< Comic >.User (String username, String password, int wallet)
Constructs a user with the specified username, password, and wallet balance.
Parameters
username the username of the user
password the password of the user
wallet the wallet balance of the user
Definition at line 44 of file User.java.
                                                            {
    this.username = username;
    this.password = password;
    this.wallet = wallet;
    this.collection = new ArrayList<>();
    this.wishlist = new ArrayList<>();
    this.tradeList = new ArrayList<>();
  }
Member Function Documentation
addToCollection()
void com.mehmetali.comic_manager.User< Comic >.addToCollection (Comic comic)
Adds a comic to the user's collection.
Parameters
comic the comic to add to the collection
Definition at line 166 of file User.java.
                                           {
    collection.add(comic);
  }
addToTradeList()
void com.mehmetali.comic_manager.User< Comic >.addToTradeList (Comic comic)
Adds a comic to the user's trade list.
Parameters
comic the comic to add to the trade list
Definition at line 202 of file User.java.
                                          {
    tradeList.add(comic);
  }
addToWishlist()
void com.mehmetali.comic_manager.User< Comic >.addToWishlist (Comic comic)
Adds a comic to the user's wishlist.
Parameters
comic the comic to add to the wishlist
Definition at line 184 of file User.java.
                                         {
    wishlist.add(comic);
  }
getCollection()
List<Comic> com.mehmetali.comic_manager.User< Comic >.getCollection ()
Gets the collection of comics owned by the user.
Returns
the collection of comics owned by the user
Definition at line 112 of file User.java.
                                     {
    return collection;
  }
getPassword()
String com.mehmetali.comic_manager.User< Comic >.getPassword ()
Gets the password of the user.
Returns
the password of the user
Definition at line 94 of file User.java.
                              {
    return password;
  }
getTradeList()
List<Comic> com.mehmetali.comic_manager.User< Comic >.getTradeList ()
Gets the trade list of comics of the user.
Returns
the trade list of comics of the user
Definition at line 148 of file User.java.
                                    {
    return tradeList;
  }
getUsername()
String com.mehmetali.comic_manager.User< Comic >.getUsername ()
Gets the username of the user.
Returns
the username of the user
Definition at line 76 of file User.java.
                              {
    return username;
  }
Referenced by com.mehmetali.comic_manager.Main.loginMenu(), com.mehmetali.comic_manager.Main.MainApp(), and com.mehmetali.comic_manager.UserManager.registerUser().
getWallet()
int com.mehmetali.comic_manager.User< Comic >.getWallet ()
Gets the wallet balance of the user.
Returns
the wallet balance of the user
Definition at line 58 of file User.java.
                         {
    return wallet;
  }
Referenced by com.mehmetali.comic_manager.UserManager.creditbuyscore(), com.mehmetali.comic_manager.UserManager.creditSellscore(), and com.mehmetali.comic_manager.Main.MainApp().
getWishlist()
List<Comic> com.mehmetali.comic_manager.User< Comic >.getWishlist ()
Gets the wishlist of comics of the user.
Returns
the wishlist of comics of the user
Definition at line 130 of file User.java.
                                   {
    return wishlist;
  }
removeFromCollection()
void com.mehmetali.comic_manager.User< Comic >.removeFromCollection (Comic comic)
Removes a comic from the user's collection.
Parameters
comic the comic to remove from the collection
Definition at line 175 of file User.java.
                                                {
    collection.remove(comic);
  }
removeFromTradeList()
void com.mehmetali.comic_manager.User< Comic >.removeFromTradeList (Comic comic)
Removes a comic from the user's trade list.
Parameters
comic the comic to remove from the trade list
Definition at line 211 of file User.java.
                                               {
    tradeList.remove(comic);
  }
removeFromWishlist()
void com.mehmetali.comic_manager.User< Comic >.removeFromWishlist (Comic comic)
Removes a comic from the user's wishlist.
Parameters
comic the comic to remove from the wishlist
Definition at line 193 of file User.java.
                                              {
    wishlist.remove(comic);
  }
setCollection()
void com.mehmetali.comic_manager.User< Comic >.setCollection (List< Comic > collection)
Sets the collection of comics owned by the user.
Parameters
collection the collection of comics owned by the user to set
Definition at line 121 of file User.java.
                                                    {
    this.collection = collection;
  }
setPassword()
void com.mehmetali.comic_manager.User< Comic >.setPassword (String password)
Sets the password of the user.
Parameters
password the password of the user to set
Definition at line 103 of file User.java.
                                           {
    this.password = password;
  }
setTradeList()
void com.mehmetali.comic_manager.User< Comic >.setTradeList (List< Comic > tradeList)
Sets the trade list of comics of the user.
Parameters
tradeList the trade list of comics of the user to set
Definition at line 157 of file User.java.
                                                  {
    this.tradeList = tradeList;
  }
setUsername()
void com.mehmetali.comic_manager.User< Comic >.setUsername (String username)
Sets the username of the user.
Parameters
username the username of the user to set
Definition at line 85 of file User.java.
                                           {
    this.username = username;
  }
setWallet()
void com.mehmetali.comic_manager.User< Comic >.setWallet (int wallet)
Sets the wallet balance of the user.
Parameters
wallet the wallet balance of the user to set
Definition at line 67 of file User.java.
                                    {
    this.wallet = wallet;
  }
Referenced by com.mehmetali.comic_manager.UserManager.creditbuyscore(), and com.mehmetali.comic_manager.UserManager.creditSellscore().
setWishlist()
void com.mehmetali.comic_manager.User< Comic >.setWishlist (List< Comic > wishlist)
Sets the wishlist of comics of the user.
Parameters
wishlist the wishlist of comics of the user to set
Definition at line 139 of file User.java.
                                                {
    this.wishlist = wishlist;
  }
toString()
String com.mehmetali.comic_manager.User< Comic >.toString ()
Returns a string representation of the user.
Returns
a string representation of the user
Definition at line 221 of file User.java.
                           {
    return "User{" +
           "username='" + username + '\'' +
           ", password='" + password + '\'' +
           ", collection=" + collection +
           ", wishlist=" + wishlist +
           ", tradeList=" + tradeList +
           '}';
  }
The documentation for this class was generated from the following file:
comic_manager_app/src/main/java/com/mehmetali/comic_manager/User.java