com.mehmetali.comic_manager.TradeManager Class Reference
Public Member Functions
TradeManager ()
int AddTrade (Trade comic)
int listAllTradeList ()
int listMyTradeList (String condition)
int deleteTradeByID (int TradeID)
int BuyTradeByID (int TradeID)
boolean isTradeNameAvailable (String title)
int getBookValueByID (int bookID)
boolean isTradeIDAvailable (int ID)
String getTradeTitleByID (int TradeID)
Detailed Description
The TradeManager class manages the trading of comic books. It handles adding, listing, deleting, and buying/selling comic books.
This class manages the list of trades and provides methods for managing trade operations.
Author
mehmetali
Version
1.0
Definition at line 20 of file TradeManager.java.
Constructor & Destructor Documentation
TradeManager()
com.mehmetali.comic_manager.TradeManager.TradeManager ()
Constructs a TradeManager object. Initializes the list of trades by reading from file.
Definition at line 32 of file TradeManager.java.
                        {
    this.comics = readUsersFromFile();
  }
Member Function Documentation
AddTrade()
int com.mehmetali.comic_manager.TradeManager.AddTrade (Trade comic)
Adds a comic book to the trade list. If the book ID is not available or the book title is already used, it returns null.
Parameters
comic The comic book to add to the trade list.
Returns
The title of the comic book if added successfully, null otherwise.
Definition at line 43 of file TradeManager.java.
                                   {
    
    if (!isTradeNameAvailable(comic.getTitle())) {
      System.out.println("This Book name is already in use. Please choose a different book name.");
      return -1;
    }
    /*
    comic.setTitle(comicmanager.getBookTitleByID(comic.getComicID()));
    comic.setpageNumber(comicmanager.getBookPageNumberByID(comic.getComicID()));
    comic.setValue(comicmanager.getBookValueByID(comic.getComicID()));
    */
    
    comics.add(comic);
    saveUsersToFile(comics);
    //comicmanager.deleteBookByID(comic.getComicID());
    System.out.println("The book has been successfully added to the Trade list.");
    return 0;
  }
References com.mehmetali.comic_manager.Trade.getTitle(), and com.mehmetali.comic_manager.TradeManager.isTradeNameAvailable().
Referenced by com.mehmetali.comic_manager.Main.TradeAddBookMenu().
BuyTradeByID()
int com.mehmetali.comic_manager.TradeManager.BuyTradeByID (int TradeID)
Buys a comic book from the trade list by its ID. Transfers the book ownership and credits between users.
Parameters
TradeID The ID of the comic book to buy from the trade list.
Returns
0 if successfully bought, -1 otherwise.
Definition at line 158 of file TradeManager.java.
                                       {
    boolean found = false;
    for (Trade comic : comics) {
      if (comic.getComicID() == TradeID) {
        
      String oldUser = comic.getuser();
      System.out.print(oldUser);
      comics.remove(comic);
      saveUsersToFile(comics);
      System.out.println("Book deleted successfully.");
      found = true;
      Book newUser = new Book(TradeID, comic.getTitle(),comic.getpageNumber(),Main.LoginName,comic.getValue());
      comicmanager.AddBook(newUser);
      usermanager.creditSellscore(Main.LoginName, comic.getValue());
      usermanager.creditbuyscore(oldUser, comic.getValue());
      return 0;
      }
    }
    if (!found) {
      System.out.println("No book matching book ID was found.");
      return -1;
    }
    return -1;
  }
References com.mehmetali.comic_manager.BookManager.AddBook(), com.mehmetali.comic_manager.UserManager.creditbuyscore(), com.mehmetali.comic_manager.UserManager.creditSellscore(), and com.mehmetali.comic_manager.Main.LoginName.
Referenced by com.mehmetali.comic_manager.Main.TradeBuyBookMenu().
deleteTradeByID()
int com.mehmetali.comic_manager.TradeManager.deleteTradeByID (int TradeID)
Deletes a comic book from the trade list by its ID. Moves the book back to the user's book list.
Parameters
TradeID The ID of the comic book to delete from the trade list.
Returns
0 if successfully deleted, -1 otherwise.
Definition at line 128 of file TradeManager.java.
                                          {
    boolean found = false;
    for (Trade comic : comics) {
      if (comic.getComicID() == TradeID) {
        comics.remove(comic);
        saveUsersToFile(comics);
        System.out.println("Book deleted successfully.");
        found = true;
        Book newUser = new Book(TradeID, comic.getTitle(),comic.getpageNumber(),comic.getuser(),comic.getValue());
        comicmanager.AddBook(newUser);
        return 0;
      }
    }
    if (!found) {
      System.out.println("No book matching book ID was found.");
      return -1;
    }
    return -1;
  }
References com.mehmetali.comic_manager.BookManager.AddBook().
Referenced by com.mehmetali.comic_manager.Main.TradedeleteBookMenu().
getBookValueByID()
int com.mehmetali.comic_manager.TradeManager.getBookValueByID (int bookID)
Returns the value of the book with the specified ID.
Parameters
bookID The ID of the book.
Returns
The value of the book with the specified ID, or 0 if the book is not found.
Definition at line 208 of file TradeManager.java.
                                          {
      for (Trade comic : comics) {
          if (comic.getComicID() == bookID) {
              return comic.getValue();
          }
      }
      return 0;
  }
Referenced by com.mehmetali.comic_manager.Main.TradeBuyBookMenu().
getTradeTitleByID()
String com.mehmetali.comic_manager.TradeManager.getTradeTitleByID (int TradeID)
Retrieves the title of a comic book by its ID.
Parameters
TradeID The ID of the comic book.
Returns
The title of the comic book if found, null otherwise.
Definition at line 241 of file TradeManager.java.
                                               {
    for (Trade comic : comics) {
      if (comic.getComicID() == TradeID) {
        return comic.getTitle();
      }
    }
    return null;
  }
isTradeIDAvailable()
boolean com.mehmetali.comic_manager.TradeManager.isTradeIDAvailable (int ID)
Checks if a trade ID is available (not already used).
Parameters
ID The ID to check availability for.
Returns
True if the ID is available, false otherwise.
Definition at line 225 of file TradeManager.java.
                                            {
    for (Trade comic : comics) {
      if (comic.getComicID() == ID) {
        return false;
      }
    }
    return true;
  }
isTradeNameAvailable()
boolean com.mehmetali.comic_manager.TradeManager.isTradeNameAvailable (String title)
Checks if a trade name is available (not already used).
Parameters
title The title to check availability for.
Returns
True if the title is available, false otherwise.
Definition at line 192 of file TradeManager.java.
                                                    {
    for (Trade comic : comics) {
      if (comic.getTitle().equals(title)) {
        return false;
      }
    }
    return true;
  }
Referenced by com.mehmetali.comic_manager.TradeManager.AddTrade().
listAllTradeList()
int com.mehmetali.comic_manager.TradeManager.listAllTradeList ()
Lists all comic books available for trade.
Returns
The number of comic books listed.
Definition at line 69 of file TradeManager.java.
                                {
    this.comics = readUsersFromFile();
    if (comics.isEmpty()) {
      System.out.println("No books found to list.");
      return 0;
    }
    System.out.println("----- Book List -----");
    for (Trade comic : comics) {
      System.out.println("Book ID: " + comic.getComicID());
      System.out.println("Title: " + comic.getTitle());
      System.out.println("Page Number: " + comic.getpageNumber());
      System.out.println("Situation: " + comic.getuser());
      System.out.println("Value: " + comic.getValue());
      System.out.println("-------------------------");
    }
    return comics.size();
  }
Referenced by com.mehmetali.comic_manager.Main.TradeAllListBookMenu().
listMyTradeList()
int com.mehmetali.comic_manager.TradeManager.listMyTradeList (String condition)
Lists the comic books available for trade by a specific condition (e.g., user).
Parameters
condition The condition to filter the comic books (e.g., user).
Returns
The number of comic books listed.
Definition at line 97 of file TradeManager.java.
                                               {
    this.comics = readUsersFromFile();
    if (comics.isEmpty()) {
      System.out.println("No books found to list.");
      return 0;
    }
    System.out.println("----- " + condition + " Books in Condition -----");
    for (Trade comic : comics) {
      if (comic.getuser().equalsIgnoreCase(condition)) {
        System.out.println("Book ID: " + comic.getComicID());
        System.out.println("Title: " + comic.getTitle());
        System.out.println("Page Number: " + comic.getpageNumber());
        System.out.println("Situation: " + comic.getuser());
        System.out.println("Value: " + comic.getValue());
        System.out.println("-------------------------");
      }
    }
    return comics.size();
  }
Referenced by com.mehmetali.comic_manager.Main.TradeMylistBookMenu().
The documentation for this class was generated from the following file:
comic_manager_app/src/main/java/com/mehmetali/comic_manager/TradeManager.java