com.mehmetali.comic_manager.BookManager Class Reference
Public Member Functions
BookManager ()
String AddBook (Book comic)
int listBooks ()
int listBooksByCondition (String condition)
int deleteBookByID (int bookID)
int updateBookTitleByID (int bookID, String newTitle, int PageNumber, int value)
boolean isBookNameAvailable (String title)
boolean isBookIDAvailable (int ID)
String getBookTitleByID (int bookID)
int getBookPageNumberByID (int bookID)
int getBookValueByID (int bookID)
Detailed Description
The BookManager class manages the collection of comic books. It provides methods for adding, listing, deleting, and updating comic books.
Author
mehmetali
Definition at line 18 of file BookManager.java.
Constructor & Destructor Documentation
BookManager()
com.mehmetali.comic_manager.BookManager.BookManager ()
Constructs a BookManager object and initializes the list of comic books by reading from a file.
Definition at line 29 of file BookManager.java.
                       {
    this.comics = readUsersFromFile(BOOK_FILE_PATH);
  }
Member Function Documentation
AddBook()
String com.mehmetali.comic_manager.BookManager.AddBook (Book comic)
Adds a new comic book to the collection.
Parameters
comic The comic book to be added.
Returns
The title of the added comic book, or null if the comic book already exists.
Definition at line 40 of file BookManager.java.
                                    {
    if (!isBookNameAvailable(comic.getTitle())) {
      return null;
    }
    comics.add(comic);
    saveUsersToFile(comics,BOOK_FILE_PATH);
    readUsersFromFile(BOOK_FILE_PATH);
    return comic.getTitle();
  }
References com.mehmetali.comic_manager.Book.getTitle(), and com.mehmetali.comic_manager.BookManager.isBookNameAvailable().
Referenced by com.mehmetali.comic_manager.Main.AddBookMenu(), com.mehmetali.comic_manager.TradeManager.BuyTradeByID(), and com.mehmetali.comic_manager.TradeManager.deleteTradeByID().
deleteBookByID()
int com.mehmetali.comic_manager.BookManager.deleteBookByID (int bookID)
Deletes a comic book from the collection based on its ID.
Parameters
bookID The ID of the comic book to be deleted.
Returns
0 if the comic book is successfully deleted, -1 otherwise.
Definition at line 114 of file BookManager.java.
                                        {
    boolean found = false;
    for (Book comic : comics) {
      if (comic.getComicID() == bookID) {
        comics.remove(comic);
        saveUsersToFile(comics,BOOK_FILE_PATH);
        System.out.println("Book deleted successfully.");
        found = true;
        return 0;
      }
    }
    if (!found) {
      System.out.println("No book matching the book ID was found.");
      return -1;
    }
    return -1;
  }
Referenced by com.mehmetali.comic_manager.Main.deleteBookMenu(), and com.mehmetali.comic_manager.Main.TradeAddBookMenu().
getBookPageNumberByID()
int com.mehmetali.comic_manager.BookManager.getBookPageNumberByID (int bookID)
Retrieves the page number of the book with the specified ID.
Parameters
bookID The ID of the book.
Returns
The page number of the book with the specified ID, or 0 if the book is not found.
Definition at line 219 of file BookManager.java.
                                               {
    for (Book comic : comics) {
      if (comic.getComicID() == bookID) {
        return comic.getpageNumber();
      }
    }
    return 0;
  }
Referenced by com.mehmetali.comic_manager.Main.TradeAddBookMenu(), and com.mehmetali.comic_manager.Main.WishAddBookMenu().
getBookTitleByID()
String com.mehmetali.comic_manager.BookManager.getBookTitleByID (int bookID)
Retrieves the title of a comic book based on its ID.
Parameters
bookID The ID of the comic book.
Returns
The title of the comic book, or null if not found.
Definition at line 202 of file BookManager.java.
                                             {
    for (Book comic : comics) {
      if (comic.getComicID() == bookID) {
        return comic.getTitle();
      }
    }
    return null;
  }
Referenced by com.mehmetali.comic_manager.WishManager.AddBook(), com.mehmetali.comic_manager.Main.TradeAddBookMenu(), and com.mehmetali.comic_manager.Main.WishAddBookMenu().
getBookValueByID()
int com.mehmetali.comic_manager.BookManager.getBookValueByID (int bookID)
Retrieves the value of the book with the specified ID.
Parameters
bookID The ID of the book.
Returns
The value of the book with the specified ID, or 0 if the book is not found.
Definition at line 235 of file BookManager.java.
                                          {
    for (Book comic : comics) {
      if (comic.getComicID() == bookID) {
        return comic.getValue();
      }
    }
    return 0;
  }
Referenced by com.mehmetali.comic_manager.Main.TradeAddBookMenu().
isBookIDAvailable()
boolean com.mehmetali.comic_manager.BookManager.isBookIDAvailable (int ID)
Checks if a given comic book ID is available in the collection.
Parameters
ID The ID of the comic book.
Returns
true if the ID is available, false otherwise.
Definition at line 187 of file BookManager.java.
                                           {
    for (Book comic : comics) {
      if (comic.getComicID() == ID) {
        return false;
      }
    }
    return true;
  }
Referenced by com.mehmetali.comic_manager.Main.WishAddBookMenu().
isBookNameAvailable()
boolean com.mehmetali.comic_manager.BookManager.isBookNameAvailable (String title)
Checks if a given comic book title is available in the collection.
Parameters
title The title of the comic book.
Returns
true if the title is available, false otherwise.
Definition at line 172 of file BookManager.java.
                                                   {
    for (Book comic : comics) {
      if (comic.getTitle().equals(title)) {
        return false;
      }
    }
    return true;
  }
Referenced by com.mehmetali.comic_manager.BookManager.AddBook().
listBooks()
int com.mehmetali.comic_manager.BookManager.listBooks ()
Lists all comic books in the collection.
Returns
The number of comic books in the collection.
Definition at line 56 of file BookManager.java.
                         {
    this.comics = readUsersFromFile(BOOK_FILE_PATH);
    if (comics.isEmpty()) {
      System.out.println("No books found to list.");
      return 0;
    }
    System.out.println("----- Book List -----");
    for (Book comic : comics) {
      System.out.println("Book ID: " + comic.getComicID());
      System.out.println("Title: " + comic.getTitle());
      System.out.println("Page Number: " + comic.getpageNumber());
      System.out.println("Situation: " + comic.getuser());
      System.out.println("Value: " + comic.getValue());
      System.out.println("-------------------------");
    }
    return comics.size();
  }
Referenced by com.mehmetali.comic_manager.Main.listAllBookMenu().
listBooksByCondition()
int com.mehmetali.comic_manager.BookManager.listBooksByCondition (String condition)
Lists comic books in the collection based on a specific condition.
Parameters
condition The condition to filter comic books.
Returns
The number of comic books satisfying the condition.
Definition at line 84 of file BookManager.java.
                                                    {
    this.comics = readUsersFromFile(BOOK_FILE_PATH);
    if (comics.isEmpty()) {
      System.out.println("No books found to list..");
      return 0;
    }
    System.out.println("----- " + condition + " Books in Condition -----");
    for (Book comic : comics) {
      if (comic.getuser().equalsIgnoreCase(condition)) {
        System.out.println("Book ID: " + comic.getComicID());
        System.out.println("Title: " + comic.getTitle());
        System.out.println("Page Number: " + comic.getpageNumber());
        System.out.println("Situation: " + comic.getuser());
        System.out.println("Value: " + comic.getValue());
        System.out.println("-------------------------");
      }
    }
    return comics.size();
  }
Referenced by com.mehmetali.comic_manager.Main.listBookMenu().
updateBookTitleByID()
int com.mehmetali.comic_manager.BookManager.updateBookTitleByID (int bookID, String newTitle, int PageNumber, int value)
Updates the title of a comic book in the collection based on its ID.
Parameters
bookID The ID of the comic book to be updated.
newTitle The new title for the comic book.
PageNumber The new PageNumbers for the comic book.
value The new value for the comic book.
Returns
0 if the comic book title is successfully updated, -1 otherwise.
Definition at line 144 of file BookManager.java.
                                                                                       {
    boolean found = false;
    for (Book comic : comics) {
      if (comic.getComicID() == bookID) {
        comic.setTitle(newTitle);
        comic.setpageNumber(PageNumber);
        comic.setValue(value);
        saveUsersToFile(comics,BOOK_FILE_PATH);
        System.out.println("The book title has been successfully updated.");
        found = true;
        return 0;
      }
    }
    if (!found) {
      System.out.println("No book matching the book ID was found.");
      return -1;
    }
    return -1;
  }
Referenced by com.mehmetali.comic_manager.Main.updateBookMenu().
The documentation for this class was generated from the following file:
comic_manager_app/src/main/java/com/mehmetali/comic_manager/BookManager.java