com.mehmetali.comic_manager.EventManager Class Reference
Public Member Functions
EventManager ()
String AddEvent (Event comic)
int listEvents ()
int listEventsByCondition (String condition)
int deleteEventByID (int EventID)
int updateEventTitleByID (int EventID, String newTitle, String newContent)
boolean isEventNameAvailable (String title)
boolean isEventIDAvailable (int ID)
String getEventTitleByID (int EventID)
Detailed Description
The EventManager class manages events in the comic manager application. It provides functionalities to add, list, delete, and update events.
This class manages the list of events and provides methods for managing events.
Author
mehmetali
Version
1.0
Definition at line 20 of file EventManager.java.
Constructor & Destructor Documentation
EventManager()
com.mehmetali.comic_manager.EventManager.EventManager ()
Constructs an EventManager object. Initializes the list of events by reading from a file.
Definition at line 30 of file EventManager.java.
                        {
    this.comics = readUsersFromFile();
  }
Member Function Documentation
AddEvent()
String com.mehmetali.comic_manager.EventManager.AddEvent (Event comic)
Adds a new event to the collection.
Parameters
comic The event to be added.
Returns
The title of the added event if successful, null otherwise.
Definition at line 40 of file EventManager.java.
                                      {
    if (!isEventNameAvailable(comic.getTitle())) {
      System.out.println("This Event name is already in use. Please choose a different Event name.");
      return null;
    }
    comics.add(comic);
    saveUsersToFile(comics);
    System.out.println("Event saved successfully.");
    return comic.getTitle();
  }
References com.mehmetali.comic_manager.Event.getTitle(), and com.mehmetali.comic_manager.EventManager.isEventNameAvailable().
Referenced by com.mehmetali.comic_manager.Main.EventAddBookMenu().
deleteEventByID()
int com.mehmetali.comic_manager.EventManager.deleteEventByID (int EventID)
Deletes an event by its ID.
Parameters
EventID The ID of the event to be deleted.
Returns
0 if the event is successfully deleted, -1 otherwise.
Definition at line 112 of file EventManager.java.
                                          {
    boolean found = false;
    for (Event comic : comics) {
      if (comic.geteventID() == EventID) {
        comics.remove(comic);
        saveUsersToFile(comics);
        System.out.println("Event deleted successfully.");
        found = true;
        return 0;
      }
    }
    if (!found) {
      System.out.println("No Event matching Event ID was found..");
      return -1;
    }
    return -1;
  }
Referenced by com.mehmetali.comic_manager.Main.EventdeleteBookMenu().
getEventTitleByID()
String com.mehmetali.comic_manager.EventManager.getEventTitleByID (int EventID)
Retrieves the title of an event by its ID.
Parameters
EventID The ID of the event.
Returns
The title of the event if found, null otherwise.
Definition at line 202 of file EventManager.java.
                                               {
    for (Event comic : comics) {
      if (comic.geteventID() == EventID) {
        return comic.getTitle();
      }
    }
    return null;
  }
isEventIDAvailable()
boolean com.mehmetali.comic_manager.EventManager.isEventIDAvailable (int ID)
Checks if an event ID is available.
Parameters
ID The ID of the event to be checked.
Returns
true if the event ID is available, false otherwise.
Definition at line 186 of file EventManager.java.
                                            {
    for (Event comic : comics) {
      if (comic.geteventID() == ID) {
        return false;
      }
    }
    return true;
  }
isEventNameAvailable()
boolean com.mehmetali.comic_manager.EventManager.isEventNameAvailable (String title)
Checks if an event name is available.
Parameters
title The title of the event to be checked.
Returns
true if the event name is available, false otherwise.
Definition at line 170 of file EventManager.java.
                                                    {
    for (Event comic : comics) {
      if (comic.getTitle().equals(title)) {
        return false;
      }
    }
    return true;
  }
Referenced by com.mehmetali.comic_manager.EventManager.AddEvent().
listEvents()
int com.mehmetali.comic_manager.EventManager.listEvents ()
Lists all events.
Returns
The number of events listed.
Definition at line 57 of file EventManager.java.
                          {
    this.comics = readUsersFromFile();
    if (comics.isEmpty()) {
      System.out.println("No Events found to list.");
      return 0;
    }
    System.out.println("----- Event List -----");
    for (Event comic : comics) {
      System.out.println("Event ID: " + comic.geteventID());
      System.out.println("Title: " + comic.getTitle());
      System.out.println("Content: " + comic.getContent());
      System.out.println("-------------------------");
    }
    return comics.size();
  }
Referenced by com.mehmetali.comic_manager.Main.EventlistAllBookMenu().
listEventsByCondition()
int com.mehmetali.comic_manager.EventManager.listEventsByCondition (String condition)
Lists events based on a condition.
Parameters
condition The condition to filter events.
Returns
The number of events listed.
Definition at line 83 of file EventManager.java.
                                                     {
    this.comics = readUsersFromFile();
    if (comics.isEmpty()) {
      System.out.println("No Events found to list.");
      return 0;
    }
    System.out.println("----- " + condition + " Events in Status -----");
    for (Event comic : comics) {
      if (comic.getUser().equalsIgnoreCase(condition)) {
        System.out.println("Event ID: " + comic.geteventID());
        System.out.println("Title: " + comic.getTitle());
        System.out.println("Content " + comic.getContent());
        System.out.println("User: " + comic.getUser());
        System.out.println("-------------------------");
      }
    }
    return comics.size();
  }
Referenced by com.mehmetali.comic_manager.Main.EventlistBookMenu().
updateEventTitleByID()
int com.mehmetali.comic_manager.EventManager.updateEventTitleByID (int EventID, String newTitle, String newContent)
Updates the title and content of an event by its ID.
Parameters
EventID The ID of the event to be updated.
newTitle The new title for the event.
newContent The new content for the event.
Returns
0 if the event title is successfully updated, -1 otherwise.
Definition at line 141 of file EventManager.java.
                                                                                   {
    boolean found = false;
    for (Event comic : comics) {
      if (comic.geteventID() == EventID) {
        comic.setContent(newContent);
        comic.setTitle(newTitle);
        saveUsersToFile(comics);
        System.out.println("Event title updated successfully.");
        found = true;
        return 0;
      }
    }
    if (!found) {
      System.out.println("No Event matching Event ID was found.");
      return -1;
    }
    return -1;
  }
Referenced by com.mehmetali.comic_manager.Main.EventupdateBookMenu().
The documentation for this class was generated from the following file:
comic_manager_app/src/main/java/com/mehmetali/comic_manager/EventManager.java